### PR TITLE
Support locale file lookup table.

### PR DESCRIPTION
**Pull request by Sjors**
This allows you to pass in a dictionary mapping locales to file paths. This can be useful if e.g. you use Grunt to rename local files to `/locales/en-{sha1}.json`.

Usage:

``` coffee
$translateProvider.useStaticFilesLoader {
  en: "locales/en.json"
  nl: "locales/nl.json"          
}
```

See also #11.

### CODE REVIEW

**Comment by knalli** [comment]
@Sjors Firstly: thank you for contribution!

 However, this is only a bower shadow repository. Please file any bugs, issues or pull requests in our main repository at https://github.com/angular-translate/angular-translate/issues

And regarding your change: 
1. Formally, please pay attention for our contribution guide lines (in the main repository).
2. I think you are abusing the (simple) static files loader. I would recommend to implement a custom loader with custom business/build logic. Additionally, I actually do not get the idea of that change. Why do you not set the pattern to `prefix='locales/', suffix='.json'`?

**Comment by knalli** [comment]
Did you intend to do

```js
$translateProvider.useStaticFilesLoader {
  en: "locales/en.someReferenceOrHash12345Id.json"
  nl: "locales/nl.someReferenceOrHash12345Id.json"          
}
```
?

Even then my point is valid: Extend a custom loader and delegate the logic to the static files loader.

**Comment by Sjors** [comment]
In my app I would write this:

```coffee
$translateProvider.useStaticFilesLoader {
  en: "locales/en.json"
  nl: "locales/nl.json"          
}
```

Grunt would then rename the locale files to e.g. `locales/en.someReferenceOrHash12345Id.json` as well as replace all occurrences of `locales/en.json` in my Javascript files with `locales/en.someReferenceOrHash12345Id.json`.

Grunt doesn't recognize those file references in javascript if the files names are composed at runtime by joining strings together.

I agree that adding these changes to `static-files-loader` doesn't make it very easy to understand and use. I'm happy to make a separate custom loader and submit a pull request for that on the `angular-translate` repository.

I'm not sure how I would delegate to the existing static files loader; as far I understand it it insists on generating the URL itself by joining prefix, key and postfix.

I'll make sure to check the guidelines.

What would be a good name for this, since "static-files-loader" is already taken?

**Comment by knalli** [comment]
Ah, I get it. You are using an additional post processor (in this case a grunt task) rewriting your code. Well, I would stick with a custom loader. For example..

```js
app.service('customLoader', function ($http, $translateStaticFilesLoader) {

	var map = {
		en: "locales/en.json",
  	nl: "locales/nl.json"        
	};

	return function (options) {
		if (map[options.lang]) {
			var mapped = map[options.lang];
      var deferred = $q.defer();
			$http(angular.extend({
  			url: mapped,
  			method: 'GET',
  			params: ''
			}, options.$http)).success(function (data) {
  			deferred.resolve(data);
			}).error(function (data) {
  			deferred.reject(options.key);
			});
      return deferred.promise;
		} else {
      return $translateStaticFilesLoader(options);
    }
	};
});
```

**Comment by knalli** [comment]
The point is: we don't want to add such special features which would be only so rarely used. The custom loader feature is mostly undervalued.

**Comment by Sjors** [comment]
It would seem quite useful to be able to cache localization files.

Without a post-processing step, you could still use ETag and
if-modified-since headers for caching, but those require a request to the
server.

Adding a hash of the file contents is also the approach used in the Rails
asset pipeline. The browser only downloads the file once and yet it never
serves outdated conent, because the file name changes whenever the content
changes.

Op maandag 20 april 2015 heeft Jan Philipp <notifications@github.com> het
volgende geschreven:

**Comment by Sjors** [comment]
I should clarify: using a hash means it only calls the server once, rather
than each time. Both caching approaches only download once per new version.

Op maandag 20 april 2015 heeft Jan Philipp <notifications@github.com> het
volgende geschreven:

**Comment by knalli** [comment]
Do you know `$http({cache: true})` (https://code.angularjs.org/1.3.15/docs/api/ng/service/$http Caching)? And additionally https://github.com/angular-translate/angular-translate/blob/a2ac7000f94bcee6dd8e206cab5d7cec3527dd25/docs/content/guide/en/12_asynchronous-loading.ngdoc#L305-L327 ?

**Comment by Sjors** [comment]
@knalli I used your custom loader with just a minor tweak here: https://github.com/blockchain/My-Wallet-HD-Frontend/commit/1da6696086d22ec2e83e760b03d20a204009ee5a#diff-1d86a618ba0b9f463c65104dda486af5

Thanks again for your help.

**Pull request closed without merging**
